language: php

branches:
  only:
    - master
    - dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer self-update
  - composer install -n --prefer-source

script:
  - vendor/bin/phpcs --standard=./phpcs.xml -v --encoding=utf-8 ./src
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml --debug --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
